### PR TITLE
[SC-225224] copy changes to upload flow

### PR DESCRIPTION
**Pull request by ehoops-cz**
### Summary:
- **What:** `Copy changes to upload flow for mpox`
- **Ticket:** [sc225224](https://app.shortcut.com/genepi/story/225224)
- **Env:** `none`

### Demos:
Screenshot 2022-11-30 at 9 26 38 AM
Screenshot 2022-11-30 at 9 27 18 AM
Screenshot 2022-11-30 at 9 31 48 AM
Screenshot 2022-11-30 at 9 31 55 AM

### Notes:
The upload flow works.  There might be a bug with parsing the metadata file - I created a [follow up ticket](https://app.shortcut.com/genepi/story/228336/follow-up-upload-tsv-metadata-bug) to look into this.

### Checklist:
- [x] I merged latest `<base branch>`
- [x] I manually verified the change
- [x] I added labels to my PR
- [x] I tested in multiple browsers
- [ ] I added relevant unit tests
- [ ] I have notified others of changes they need to make locally (migrations, jobs, package updates, etc)

### CODE REVIEW

**Review by lvreynoso — APPROVED** [review]
lgtm

**Comment by ehoops-cz** [comment]
- [x] Update nextstrain defaults link in instructions to go here: https://docs.nextstrain.org/projects/ncov/en/latest/reference/metadata-fields.html

**Review by Janeece — APPROVED** [review]
Looks great, thanks @ehoops-zz !

**Comment by ehoops-cz** [comment]
Screenshot 2022-11-30 at 2 54 59 PM

**Pull request merged**
