### PR TITLE
[easy] Remove schema.ddl

### PR DESCRIPTION
**Pull request by ttung**
### Description
It's out of date anyway.

### Test plan
YOLO

### CODE REVIEW

**Comment by sidneymbell** [comment]
Can we keep (and update) this, actually? It's super helpful to me.

**Comment by ttung** [comment]
> Can we keep (and update) this, actually? It's super helpful to me.

oh man, that will be quite an undertaking...

**Review by shanaxel42 — APPROVED** [review]
Love a good tony yolo pr

**Comment by ttung** [comment]
> Can we keep (and update) this, actually? It's super helpful to me.

@sidneymbell  I created #270.  It's a compromise between dumping it and updating it (and continually updating it) by hand, which is a big commitment.  Let me know what you think.

**Comment by sidneymbell** [comment]
That's a great path, thank you Tony!

**Pull request closed without merging**
