### PR TITLE
Sample Filtering -- Feature flag and basic setup

### PR DESCRIPTION
**Pull request by vincent-czi**
### Summary:
- **What:** Usage of new Split feature flags, basic setup of Sample Filtering behind feature flag
- **Ticket:** [sc<184605>](https://app.shortcut.com/genepi/story/<184605>)
- **Env:** https://sample-filtering-setup-frontend.dev.czgenepi.org/
  - **NOTE** If you're logging in to the rdev, make sure you are logged in with your _personal_ work email account, not a smoke test account. Feature flags are currently tied to the user account, and it's our work emails that are in the group that can see what's behind the flag. (@mmmmmmaya For you specifically, things will blow up right now if you use your personal account in the rdev. Sorry! Because you hadn't previously gotten a personal account, it's not one of the accounts that's tracked in the rdev DB yet, so you'll go into a never-ending login loop. I'll try to fix that later today so future rdevs work as expected for you.)

### Demos:
image

### Notes:
The dropdowns are a bit more difficult to build than I had orginally expected. As such, they're really, really dummy placeholders right now. Roughly the right visual look, but they'll be completely re-implemented in the next PR or two so I wouldn't worry about them too much.

I wrote up a [guide on the wiki](https://czi.atlassian.net/l/c/Tux80FVg) for making a new feature flag so -- for simple flags at least -- you can just quickly run through the process if you're not familiar with Split already.

### Checklist:
- [x] I merged latest `trunk`
- [x] I manually verified the change
- [x] I added labels to my PR
- [ ] I tested in multiple browsers
- [ ] I added relevant unit tests
~I have notified others of changes they need to make locally (migrations, jobs, package updates, etc)~ (none needed)

### CODE REVIEW

**Review by mmmmmmaya — APPROVED** [review]
The linked doc and inline comments are very thorough and easy to understand 👏

**Review by Janeece — COMMENTED** [review]
@vincent-czi this looks great. I have 2 refinements to request, neither are blockers:

- [ ] Increase the "lineage" and "collection date" headers to fontHeaderXs (12pt to 13pt) — this was a design spec mistake, sorry! Screen Shot 2022-03-14 at 9 48 49 AM

- [ ] Update tooltip link's hover state to be primary500 and no underline. Screen Shot 2022-03-14 at 9 50 04 AM

**Comment by vincent-czi** [comment]
Design feedback addressed. Talked with Janeece, wound up actually being Primary600 that was needed.

Since change is small and I verified it locally, not going to refresh the rdev.

**Comment by mmmmmmaya** [comment]
changes lgtm. ff to merge.

**Review by jgadling — APPROVED** [review]

**Pull request merged**
