### PR TITLE
Update setup docs.

### PR DESCRIPTION
**Pull request by jgadling**
### Summary:
- **What:** Fix up our onboarding docs to include a more condensed intstall/setup guide

### Checklist:
- [x] I merged latest `<base branch>`
- [x] I manually verified the change
- [x] I added labels to my PR
- [ ] I tested in multiple browsers
- [ ] I added relevant unit tests
- [ ] I have notified others of changes they need to make locally (migrations, jobs, package updates, etc)

### CODE REVIEW

**Review by danrlu — APPROVED** [review]
i shall be the guinea pig to try them out later today

**Comment by jgadling** [comment]
> i shall be the guinea pig to try them out later today

I'll leave this open so we can fix it before merging!

**Review by vincent-czi — APPROVED** [review]
Looks good!

**Comment by phoenixAja** [comment]
thanks for doing this!

**Pull request merged**
