### PR TITLE
[ch153503] phylo tree help link

### PR DESCRIPTION
**Pull request by mmmmmmaya**
### Summary
- **What:** Add help link to tree page
- **Ticket:** [[ch153503]](https://app.clubhouse.io/genepi/story/153503)
- **Env:** https://helplink-frontend.dev.genepi.czi.technology/data/phylogenetic_trees

### Demos
after

### Checklist
- [x] I merged latest `feat/filtering`
- [x] I manually verified the change
- [x] I added labels to my PR
- [ ] I tested in multiple browsers
- [ ] I added relevant unit tests
- [ ] I have notified others of changes they need to make locally (migrations, jobs, package updates, etc)

### CODE REVIEW

**Review by phoenixAja — APPROVED** [review]
lgtm! janeece might want an rdev to add her review (she likes to check the stylings with inspect)

**Comment by Janeece** [comment]
Heck yeah I do!
@mmmmmmaya this looks great. My only comment is that we should have the link open in a new tab so user isnt taken out of Aspen.

**Comment by mmmmmmaya** [comment]
@Janeece just updated it. can you let me know if it looks good now? ty!

**Review by Janeece — APPROVED** [review]
@mmmmmmaya works great, thank you! all good with me.

**Pull request merged**
