### PR TITLE
added instructions for starting flask app

### PR DESCRIPTION
**Pull request by phoenixAja**
### Description

adding some basic instructions to run app in development mode

### Test plan

follow instructions to run app

### CODE REVIEW

**Review by lvreynoso — APPROVED** [review]
lgtm, i'll add a gunicorn command too in a separate PR.

**Comment by ttung** [comment]
Do we have to run `npm ts build`?

**Comment by lvreynoso** [comment]
~~If you're only doing backend dev you can run `npm --prefix src/ts build`.~~ nvm, see below

**Comment by phoenixAja** [comment]
> Do we have to run `npm ts build`?

i'll add a step in the readme to do this part/ link the frontend docs

**Comment by lvreynoso** [comment]
I suggest doing `npm --prefix src/ts start`, since if you're switching branches or merging in code it will pick up frontend changes automatically

**Comment by phoenixAja** [comment]
alright i added it in, thanks for the input on npm @lvreynoso

**Pull request merged**
