### PR TITLE
thuang-tos-typo-fix

### PR DESCRIPTION
**Pull request by tihuan**
### Description

Write a description of your pull request here

#### Issue
[ch<fill_in_issue_number>](https://app.clubhouse.io/genepi/story/<fill_in_issue_number>)

### Test plan

Write how your changes are tested, or give a convincing reason why they can't be tested automatically.

### CODE REVIEW

**Comment by tihuan** [comment]
quick typo fix so I'll not spam people with review requests 😆 Thank you!

**Comment by tihuan** [comment]
@jshoe found this! THANKS AGAIN!

**Review by jshoe — APPROVED** [review]

**Comment by jshoe** [comment]
haha just prepping for the bug bash

**Comment by tihuan** [comment]
We got a head start 😆👌 !

**Comment by tihuan** [comment]
Ah seems like Github wants someone with write access to approve this 🙏 

@shanaxel42 can you add me to this repo as an Admin please? That would help with force merging this type of trivial PRs 🙏 Thank you!

**Review by ttung — APPROVED** [review]
lolz.

**Pull request merged**
