### PR TITLE
fine tune where we ignore missing imports

### PR DESCRIPTION
**Pull request by ttung**
### Description
Rather than ignoring all missing imports, be explicit about which missing imports are okay.  It's discouraged in the [docs](https://mypy.readthedocs.io/en/stable/running_mypy.html), but I'm not sure if it's that valuable.  Open to a debate whether we should do this or not.

Depends on #212

### Test plan
make -j style

### CODE REVIEW

**Comment by phoenixAja** [comment]
did you mean to delete `src/py/aspen/__main__.py`?

**Comment by ttung** [comment]
> did you mean to delete src/py/aspen/__main__.py?

yeah, do we still need it? it refers to modules that don't even exist any more, so I would be surprised if we need it.

**Comment by phoenixAja** [comment]
so whenever we add a new third party library would we have to update` .mypy.ini`? we should add something to the docs about when/how to update that file.

**Comment by phoenixAja** [comment]
> > did you mean to delete src/py/aspen/**main**.py?
> 
> yeah, do we still need it? it refers to modules that don't even exist any more, so I would be surprised if we need it.

i guess you're right i was just checking

**Review by phoenixAja — APPROVED** [review]

**Review by shanaxel42 — APPROVED** [review]

**Comment by ttung** [comment]
> so whenever we add a new third party library would we have to update .mypy.ini? we should add something to the docs about when/how to update that file.

It's for third-party libraries that do not support typing that we would need to do this.

**Comment by ttung** [comment]
added [docs](https://github.com/chanzuckerberg/aspen/pull/213/files#diff-7a686e36c672a51917b2c3fc53bbf84890ca2ce8383c8caa5395ecf949fbe609).

**Pull request merged**
