### PR TITLE
turn on sample filtering

### PR DESCRIPTION
**Pull request by mmmmmmaya**
### Summary
- **What:** Turn on sample filtering
- **Env:** https://samplefiltering-frontend.dev.czgenepi.org/
- **Design:** https://www.figma.com/file/nGRxk2lhJoWoiPSnM0GY8g/Self-Serve-Tree-V4---Sample-Filtering?node-id=2667%3A183591

### Testing
Already tested and design reviewed.

### Checklist
- [x] I merged latest `trunk`
- [x] I manually verified the change
- [x] I added labels to my PR
- [x] I either asked design for a review or hid my changes behind a feature flag
- [ ] I tested in multiple browsers
- [ ] I added relevant unit tests
- [ ] I have notified others of changes they need to make locally (migrations, jobs, package updates, etc)

### CODE REVIEW

**Comment by danrlu** [comment]
I was building trees on staging and saw this so I poked around. Looks great 🤩 🤩 🤩 

- This`Learn More` here should link out to: https://docs.google.com/document/d/1_iQgwl3hn_pjlZLX-n0alUbbhgSPZvpW_0620Hk_kB4/edit?usp=sharing

image

- (Nice to have) Can we sort the lineages (the same way as the lineage filter in sample table view)? 
image

All others look great!! Thanks Maya <3

**Comment by vincent-czi** [comment]
@danrlu 

> * This`Learn More` here should link out to: https://docs.google.com/document/d/1_iQgwl3hn_pjlZLX-n0alUbbhgSPZvpW_0620Hk_kB4/edit?usp=sharing
> 
> image

Wait, really? That seems surprising to me. That "Learn More" link currently in the tooltip just above the filtering dropdowns goes to the Google Doc that specifies how the "Customized Tree Builds" (Sample Filtering) works. https://docs.google.com/document/d/1NhDW42YZQ7DMhPhUOIBWp04n51FO8GItCZPaw7hRtQk

The link you put in the note goes to the general "Phylogenetic Tree Building Guide", which is the same as the link we curently have in the "Read our guide to learn more" tooltip next to the Tree Type selection. https://docs.google.com/document/d/1_iQgwl3hn_pjlZLX-n0alUbbhgSPZvpW_0620Hk_kB4

image

The link locations as they currently are in the rdev seem correct to me.

---

> * (Nice to have) Can we sort the lineages (the same way as the lineage filter in sample table view)?

I don't know if it matters, but when I set this up, I didn't touch the order at all for the lineages in the new Sample Filtering section, so -- I'm pretty sure -- they wind up coming in the same order they are presented in the [`lineage_notes.txt`](https://raw.githubusercontent.com/cov-lineages/pango-designation/master/lineage_notes.txt) over in cov-lineages, which -- I'm pretty sure again -- winds up matching the order on the [website version of that list they host](https://cov-lineages.org/lineage_list.html). I don't know if that provides any value, but wanted to point it out just in case that actually is useful at all.

**Comment by danrlu** [comment]
Sorry for the confusion! This is [the doc](https://docs.google.com/document/d/1qjS6gRaKwpiw8WE2LbBNh9-m5ZFXm9X_H7O6UsXXiAw/edit?usp=sharing) that will get copied over to the link I suggested above together with feature release. That specific tooltip should like out to the lineage/date filter section of this file but we won't have its URL until it's copied over, so I'll further update it after the feature release (very good point in reminding me this, thanks Vincent!)

For lineages, I looked around and I don't think they sorted it in a meaningful way (but good precautions). It's good if we could sort it on our end, but this is good to have, not a must have! 

Thanks very much!

**Review by vincent-czi — APPROVED** [review]
Looks good! Just make sure to double-check with Lucia before merging to verify the bugfix is complete for getting the sample filtering to not explode when it hits the backend

**Comment by phoenixAja** [comment]
🎉 🎉 🎉

**Pull request merged**
