### PR TITLE
Maya/168693 sds warnings

### PR DESCRIPTION
**Pull request by mmmmmmaya**
### Summary
- **What:** Eliminated all console warnings from use of czifui `Button` component which originate from our app
- **Why:** To make front end debugging easier and to adhere to sds guidelines
- **Ticket:** [[sc-168693]](https://app.shortcut.com/genepi/story/168693)
- **Env:** https://gisaidlogo-frontend.dev.czgenepi.org/

### Demos
No visual changes.

### Notes
- I did manually check each button as I was updating it, but you may want to spot check.
- SDS generates some of these errors, so it does not eliminate all the warnings :(
- It might be easiest to view the [straightforward conversions](https://github.com/chanzuckerberg/czgenepi/pull/993/commits/0687ae9660722b7a49c7411c59c1b1eb17e0c38d) commit on its own at first, and then everything else after

### Checklist
- [x] I merged latest `trunk`
- [x] I manually verified the change
- [x] I added labels to my PR
- [ ] I either asked design for a review or hid my changes behind a feature flag
- [ ] I tested in multiple browsers
- [ ] I added relevant unit tests
- [ ] I have notified others of changes they need to make locally (migrations, jobs, package updates, etc)

### CODE REVIEW

**Comment by phoenixAja** [comment]
code looks good but i'm getting a 502 gateway error on the rdev

**Review by phoenixAja — COMMENTED** [review]
code looks good but i'm getting a 502 gateway error on the rdev. 

Thanks for the extra cleanup for the fasta download!

**Comment by mmmmmmaya** [comment]
@phoenixAja  sorry! the pr was open so long I forgot that rdev was still valid. I made a new one at https://sdswarn-frontend.dev.czgenepi.org

**Review by phoenixAja — APPROVED** [review]
looks good!! (sorry didn't see your earlier comment on the fixed rdev)

**Pull request merged**
