### PR TITLE
Remove tree-location-filter feature flag.

### PR DESCRIPTION
**Pull request by ehoops-cz**
### Summary:
- **What:** `Remove tree-location-filter feature flag which was used for development - the feature has been released for some time.`
- **Ticket:** none
- **Env:** `none`

### Demos:
Screenshot 2023-01-04 at 9 44 38 AM
Screenshot 2023-01-04 at 9 44 43 AM
Screenshot 2023-01-04 at 9 44 48 AM

### Checklist:
- [x] I merged latest `<base branch>`
- [x] I manually verified the change
- [x] I added labels to my PR
- [x] I tested in multiple browsers
- [ ] I added relevant unit tests
- [ ] I have notified others of changes they need to make locally (migrations, jobs, package updates, etc)

### CODE REVIEW

**Comment by ehoops-cz** [comment]
@Janeece if you could read through the copy on the screenshots, that would be great.  This change should make the updates permanent, but I want to make sure I didn't accidentally copy/pasta the old ones.

**Comment by Janeece** [comment]
> @Janeece if you could read through the copy on the screenshots, that would be great. This change should make the updates permanent, but I want to make sure I didn't accidentally copy/pasta the old ones.

@ehoops-zz Looks like the screenshots' copy is missing the updates for the gray text descriptions (all tree types) and bullet points below targeted and non-contextualized. There's [notes in the design doc](https://www.figma.com/file/X2LRJ74hSEpGfR4c225XGc/Create-Tree-Location-Filter?node-id=166%3A70067&t=XlLE0b3i0BZr90vF-1), but let me know if you need screenshots to clarify.

**Comment by ehoops-cz** [comment]
> > @Janeece if you could read through the copy on the screenshots, that would be great. This change should make the updates permanent, but I want to make sure I didn't accidentally copy/pasta the old ones.
> 
> @ehoops-cz Looks like the screenshots' copy is missing the updates for the gray text descriptions (all tree types) and bullet points below targeted and non-contextualized. There's [notes in the design doc](https://www.figma.com/file/X2LRJ74hSEpGfR4c225XGc/Create-Tree-Location-Filter?node-id=166%3A70067&t=XlLE0b3i0BZr90vF-1), but let me know if you need screenshots to clarify.

Thanks Janeece!  I had updated only the monkeypox copy (which we don't even use yet 😅 ).  Updated now:
Screenshot 2023-01-04 at 3 25 00 PM

**Comment by Janeece** [comment]
> Thanks Janeece! I had updated only the monkeypox copy (which we don't even use yet 😅 ).

@ehoops-zz It's really hard with all these future designs floating around, I get mixed up too 🫠 

Gray text looks good to me, Did you also update the checkmark "bullets"? 
We could just go with the [MPX v1 copy](https://www.figma.com/file/qad76DF1RVVGlYa2iTgQD2/Monkeypox?node-id=406%3A189978&t=kppDxFTKiAujbhY3-1)...but maybe it'll help us keep track if we just take it one step at a time.

**Review by mmmmmmaya — APPROVED** [review]

**Comment by ehoops-cz** [comment]
> > Thanks Janeece! I had updated only the monkeypox copy (which we don't even use yet 😅 ).
> 
> @ehoops-zz It's really hard with all these future designs floating around, I get mixed up too 🫠
> 
> Gray text looks good to me, Did you also update the checkmark "bullets"? We could just go with the [MPX v1 copy](https://www.figma.com/file/qad76DF1RVVGlYa2iTgQD2/Monkeypox?node-id=406%3A189978&t=kppDxFTKiAujbhY3-1)...but maybe it'll help us keep track if we just take it one step at a time.

I didn't I'll leave that for the mpx ticket just so it doesn't get too confusing 😅

**Comment by Janeece** [comment]
@ehoops-cz oh there is updates needed for some the bullets too that are related to the change to adding the locations filter, noted here:
Screenshot 2023-01-05 at 3 52 48 PM
Screenshot 2023-01-05 at 3 52 59 PM

Again, sorry that it's kinda confusing about what updates are related to what!

**Pull request merged**
