### PR TITLE
Suggest that deployments go to separate environments

### PR DESCRIPTION
**Pull request by ttung**
### Description
No reason we should all be stomping over each other with -staging.

### Test plan
it's documentation <shrug>

### CODE REVIEW

**Comment by phoenixAja** [comment]
for this to work do we have to create the eb environment before hand or will it automatically create it for us?

**Comment by ttung** [comment]
> for this to work do we have to create the eb environment before hand or will it automatically create it for us?

Good point, let me fix it.  It's an extra step but pretty straightforward.

**Comment by ttung** [comment]
Ok fixed!

**Review by lvreynoso — APPROVED** [review]

**Review by phoenixAja — APPROVED** [review]
sweet

**Pull request merged**
