### PR TITLE
Update @svgr/webpack to ^6.2.1 to get nth-check ^2.0.1

### PR DESCRIPTION
**Pull request by lvreynoso**
### Summary:
- **What:** Mitigates [Dependabot security alert 2](https://github.com/chanzuckerberg/czgenepi/security/dependabot/2).
- **Ticket:** [sc<fill_in_issue_number>](https://app.shortcut.com/genepi/story/<fill_in_issue_number>)
- **Env:** [https://nth-frontend.dev.czgenepi.org/](https://nth-frontend.dev.czgenepi.org/)

### Checklist:
- [x] I merged latest `<base branch>`
- [x] I manually verified the change
- [x] I added labels to my PR
- [x] I tested in multiple browsers
- [x] I added relevant unit tests
- [ ] I have notified others of changes they need to make locally (migrations, jobs, package updates, etc)

### CODE REVIEW

**Comment by lvreynoso** [comment]
Looks like this needs some webpack config editing, working on it.

**Comment by lvreynoso** [comment]
Fixed the webpack config! https://nth-frontend.dev.czgenepi.org/

**Comment by mmmmmmaya** [comment]
Unfortunately, the webpack config is not valid and breaks the styling on the homepage animation. See before and after:
before

after

**Review by mmmmmmaya — CHANGES_REQUESTED** [review]
Animation on hp broken

**Comment by mmmmmmaya** [comment]
@lvreynoso Is there a ticket or some way to track that this work still needs to be done?

**Comment by lvreynoso** [comment]
No, this is just captured by "on-call duties".

**Comment by vincent-czi** [comment]
@mmmmmmaya It's still tracked by looking at current Dependabot alerts: https://github.com/chanzuckerberg/czgenepi/security/dependabot

**Pull request closed without merging**
