### PR TITLE
Normalize the singular/plural

### PR DESCRIPTION
**Pull request by ttung**
### Description
1. `processed_gisaid_dump` should be `processed_gisaid_dumps` because it returns a sequence.
2. Make all the python entities singular (i.e., `SequencingRead`).

#### Issue
[ch64743](https://app.clubhouse.io/genepi/stories/space/64743)

### Test plan
GA

### CODE REVIEW

**Comment by ttung** [comment]
The only part of this that is potentially questionable is `SequencingRead`.  I know it's really multiple reads, but keeping a consistent pluralization is helpful for devs.  @jackkamm  is this a showstopper? :)

**Review by erinstargazer — COMMENTED** [review]
I think `SequencingRead` also needs to be updated in the `backend/schema.ddl` doc.

**Comment by jackkamm** [comment]
`SequencingRead` does read really strange to me. A better choice might be one of `SequencingReadsCollection`, `SequencingReadsPool`, or `SequencingReadsLibrary`. I'm not 100% confident of the terminology, someone with a stronger molecular background should comment, maybe @danrlu ?

**Comment by erinstargazer** [comment]
> `SequencingRead` does read really strange to me. A better choice might be one of `SequencingReadsCollection`, `SequencingReadsPool`, or `SequencingReadsLibrary`. I'm not 100% confident of the terminology, someone with a stronger molecular background should comment, maybe @danrlu ?

That's a good point. The current suggestions do sounds a bit odd as well (although no as much). It's really more along the lines of a sequencing run produces a fasta that has the reads. So something along the lines of `SequencingRun` (although that doesn't really capture that this is specific to reads) or `SequencingFasta` or even `ReadsFromSequeneRun` (very verbose) seems to match reality more without adding a modifier like `Pool` (I personally don't feel that adds clarification), `Library` (you can have multiple runs with the same library so this also seems a bit confusing) or `Collection` (this is the clearest of these from my perspective).

**Comment by danrlu** [comment]
I agree that `Pool` and `Library` means specific things in sequencing. `SequencingRead` sounds good to me, `SequencingFastq` or the good old `SampleFastq` too (me non-native speaker alert!). The actual table name is `sequencing_reads` + consistent singular in py code should be least confusing to ppl.

**Comment by ttung** [comment]
I renamed it to `SequencingReadCollection` and `HostFilteredSequencingReadCollection`.  It's a mouthful, but hopefully we're not mucking around there too often?  :)

Added a migration, and updated `schema.ddl`.

**Review by phoenixAja — APPROVED** [review]

**Pull request merged**
