### PR TITLE
Support creating a single phylorun for debugging

### PR DESCRIPTION
**Pull request by jgadling**
### Summary:
- **What:** `<brief description>`
- **Ticket:** [sc<fill_in_issue_number>](https://app.shortcut.com/genepi/story/<fill_in_issue_number>)
- **Env:** `<rdev link>`

### Checklist:
- [ ] I merged latest `<base branch>`
- [ ] I manually verified the change
- [ ] I added labels to my PR
- [ ] I tested in multiple browsers
- [ ] I added relevant unit tests
- [ ] I have notified others of changes they need to make locally (migrations, jobs, package updates, etc)

### CODE REVIEW

**Comment by danrlu** [comment]
Thanks very much Jess 🤩 

1. I tried it out and it gave this error (after rebuilding the tree docker):
image

I Googled around, [here](https://github.com/hidaris/thingtalk/issues/9) says `cached_property` is only in Python 3.8? The step above is already in the tree docker, right? If so, Nextstrain docker base is still Python 3.7
https://github.com/nextstrain/docker-base/blob/6a5b942b6497243821c37f12f764443904983008/Dockerfile#L8
image


2. Do I need to change the input json(from the code it looks like group can take either id or name?):
```{"genepi_config_secret_name":"gestaging/genepi-config",
"aws_region":"us-west-2",
"group":"San Luis Obispo County Health Agency, Public Health Laboratories",
"remote_dev_prefix":"",
"s3_filestem":"San Luis Obispo",
"template_args":"{\"division\":\"California\",\"location\":\"San Luis Obispo County\"}",
"tree_type":"OVERVIEW"}
```

3. py-lint had a few notes, just copying here since I was looking (to see whether I could fix them... no I can't lol)
image

Let me know what else I can do! (No rush, I'm just trying to update the ncov pin)

**Comment by jgadling** [comment]
>     1. I tried it out and it gave this error (after rebuilding the tree docker):
> 
> 
> image
> 
> I Googled around, [here](https://github.com/hidaris/thingtalk/issues/9) says `cached_property` is only in Python 3.8? The step above is already in the tree docker, right? If so, Nextstrain docker base is still Python 3.7 https://github.com/nextstrain/docker-base/blob/6a5b942b6497243821c37f12f764443904983008/Dockerfile#L8 image

OOOH, excellent find. we are (were?) stuck on python 3.7 for any containers that run nextstrain, since their tools weren't updated for python 3.8+. I'll look into whether we can drop the use of `cached_property` or whether we can upgrade nextstrain images.

**Comment by jgadling** [comment]
can you try this again @danrlu ?

**Comment by danrlu** [comment]
Any ideas?
image
Input json is (I tried with or without `aws_region`)
```
{"genepi_config_secret_name":"gestaging/genepi-config",
"aws_region":"us-west-2",
"group":"San Luis Obispo County Health Agency, Public Health Laboratories",
"remote_dev_prefix":"",
"s3_filestem":"San Luis Obispo",
"template_args":"{\"division\":\"California\",\"location\":\"San Luis Obispo County\"}",
"tree_type":"OVERVIEW"}
```

**Comment by vincent-czi** [comment]
@danrlu: Unless we have something special doing the key interpretation -- and I don't think that's the case here, it just looks like a standard key access from what I can see in the stack trace -- capitalization matters `AWS_REGION` (from the error) and `aws_region` (from the json you posted) will not match up. If you did a test with all caps AWS_REGION though, disregard, something weirder is going on.

**Review by danrlu — APPROVED** [review]
Thank you!

**Comment by danrlu** [comment]
this merge will also bring in ncov update

**Pull request merged**
