### PR TITLE
thuang-click-through-tos-122409

### PR DESCRIPTION
**Pull request by tihuan**
### Description

1. Add Agree ToS page `/agreeTerms`
2. Add placeholder pages for `/terms`, `/privacy`, and `/faq`
3. Add `<ProtectedRoute />` component to kick user out of protected pages, such as Samples
4. BE: Update `usergroup.py` to remove `json.loads()` since `request.get_json()` already returns a JSON dict, which caused a runtime error (@phoenixAja PTAL 🙏 Thank you!)
5. Update `<App />` component to block loading content while fetching user data, so we want determine whether we should send them to `/agreeTerms` page
6. Add `updateUserData()` PUT API call and `logout()` API call
7. Add component Dialog matching [specs in Figma](https://www.figma.com/file/uHpPNuDSBupK97ORCkH1op/Aspen-v0-and-v2?node-id=72%3A3911). I didn't have time to pull that into the component library yet, due to the time crunch. Will do it next week!
8. Add List and Link components in component library [PR](https://github.com/chanzuckerberg/sci-components/pull/19)

#### Issue
https://app.clubhouse.io/genepi/story/122409/add-tos-clickthrough-to-aspen-site-upon-user-s-first-login

### Test plan

1. Visit live link: https://thuang-agree-tos-frontend.dev.genepi.czi.technology (currently not working, rdev seems to need database migration?) --- use local dev first!
2. Log in as a user
3. You should get redirected to `/agreeTerms`
4. Click "Decline" and nothing will happen, because I think Auth0 logout is not working yet
5. Click "Accept" and you will get dropped into Samples page!

Screen Shot 2021-04-29 at 7 43 39 AM

demo

### CODE REVIEW

**Comment by phoenixAja** [comment]
> 1. Visit live link: https://thuang-agree-tos-frontend.dev.genepi.czi.technology (currently not working, rdev seems to need database migration?) --- use local dev first!

@jgadling looks like the mysterious migrations issue is back 😞

**Comment by phoenixAja** [comment]
@tihuan [i have a patch for you](https://github.com/chanzuckerberg/aspen/pull/314) that will fix the tests for your recent changes to the usergroup view!

**Review by phoenixAja — APPROVED** [review]
YAYY!! LGTM!

**Comment by tihuan** [comment]
WOOHOO! GOGOGO!!

**Pull request merged**
