### PR TITLE
Switch frontend to use v2 list samples

### PR DESCRIPTION
**Pull request by lvreynoso**
### Summary:
- **What:** Switches frontend to use v2 list samples added in #784 
- **Ticket:** [sc<fill_in_issue_number>](https://app.shortcut.com/genepi/story/<fill_in_issue_number>)
- **Env:** `<rdev link>`

### Notes:
This will help with filling in missing/"NaN" locations, since the code to deal with it is in the v2 endpoint, added in #821 

### Checklist:
- [x] I merged latest `<base branch>`
- [x] I manually verified the change
- [x] I added labels to my PR
- [x] I tested in multiple browsers
- [x] I added relevant unit tests
- [x] I have notified others of changes they need to make locally (migrations, jobs, package updates, etc)

### CODE REVIEW

**Comment by mmmmmmaya** [comment]
This actually messes up the UI for the samples table, since the dates that are returned aren't the same format. I have the full set of changes required in another PR (#825).

**Comment by lvreynoso** [comment]
I can also change the endpoint to return just the **date** for upload_date, I'm not sure the time is really necessary

**Comment by mmmmmmaya** [comment]
I think this change was intentional, to better support different time zones in the future.

**Comment by lvreynoso** [comment]
Right! Thanks for reminding me.

**Comment by mmmmmmaya** [comment]
I think this PR can be closed out, since #825 was merged in.

**Pull request closed without merging**
