### PR TITLE
Maya/166265 phylotree zero samples

### PR DESCRIPTION
**Pull request by mmmmmmaya**
### Summary
- **What:** 
  - Add gisaid ingest feature flag
  - Enable phylo tree button from sample table view, even when no samples are selected
  - Disable the usher option in the menu when no samples are selected
  - Also add a tooltip to tell user why usher menu item is disabled
- **Ticket:** [[sc-166265]](https://app.shortcut.com/genepi/story/166265)
- **Env:** https://gisaidingest-frontend.dev.genepi.czi.technology/data/samples?gisaidIngest=true

### Demos
Screen Shot 2021-10-27 at 9 08 31 PM
Screen Shot 2021-10-27 at 9 08 50 PM
Screen Shot 2021-10-27 at 9 08 42 PM

### Checklist
- [x] I merged latest `trunk`
- [x] I manually verified the change
- [x] I added labels to my PR
- [ ] I tested in multiple browsers
- [ ] I added relevant unit tests
- [ ] I have notified others of changes they need to make locally (migrations, jobs, package updates, etc)

### CODE REVIEW

**Comment by Janeece** [comment]
@mmmmmmaya wow this is looking great! 
- [x] Can we make the tooltip the white version instead? (You implemented correctly, Design very recently refined our tooltip usage guidelines and this one would now be the white type)
- [ ] When I open the dropdown menu the page content widens because the scroll disappears -- could we prevent this?

GISAID menu

**Review by phoenixAja — APPROVED** [review]
🎏 🎏 🎏

**Comment by mmmmmmaya** [comment]
@Janeece I updated the tooltip, but I'm not seeing the gap you're seeing. Which browser are you using?
scroll

**Comment by mmmmmmaya** [comment]
Screen Shot 2021-10-28 at 12 50 58 PM

**Comment by Janeece** [comment]
> @Janeece I updated the tooltip, but I'm not seeing the gap you're seeing. Which browser are you using?

@mmmmmmaya how strange! I'm on Chrome (Version 95.0.4638.69)

Tooltip looks great, thanks for making that update!

**Pull request merged**
