### PR TITLE
Samples Upload

### PR DESCRIPTION
**Pull request by phoenixAja**
### Description

first part of the upload process (upload samples)

#### Issue
[ch119808](https://app.clubhouse.io/genepi/story/119808)

### Test plan

tested locally and in rdev! 
https://samples-upload-frontend.dev.genepi.czi.technology/

### CODE REVIEW

**Comment by Janeece** [comment]
@phoenixAja First, I just want to say that this looks really amazing! 

Here's my prioritized list of comments. Let me know if you have any questions. I will follow up with more details on the error accordion and warning modal. 

#### Prioritization Key:
**[Must Have]** - change needed to meet required v3 specs
**[Should Have / Design Priority]** - update needed to create a clear user experience & accurately reflect design, does not prevent feature function.
**[Low priority]** - nice to haves, minor refinements

## Feedback
#### Screenshots
Aspen-Upload-Sample no samples
Aspen-Upload-Sample samples table with error

#### Nav Upload button
- **[Must Have]** Needs to match to @tihuan  implementation
#### More/Less Info button and “Remove All” button
- **[Should Have - Design Priority]** Text button component needs to be updated
  - Text style = $font-caps-xxxs
  - No background on  hover
  - Text hover color $primary-dark / $primary-500
#### File Instructions
- **[Low Priority]** Reduce text size to $font-body-xs
- **[Low Priority]** Reduce Space between instructions and  “Upload Fasta files” button to $space-l (14px)
#### Error Accordion
- **[Should Have - Design Priority]** Move below “Select Fasta Files” button
- **[Should Have - Design Priority]** Update component to match design system specs -- janeece to send more info
#### Sample List table
- **[Low Priority]** Add $space-m (10px) margin on right side of columns so that we keep space between content on small windows/long content names.
- **[Low Priority]** Reduce space between table and cancel/continue buttons to $space-xxl (38px) -- currently both bottom of table and top of button have $38px margin so space is doubled
#### Continue/Cancel Buttons
- **[Must Have]** Recommend matching @tihuan implementation. 
  - Position buttons $space-xl (22px) from the bottom of the page
  - Remove space on left of “Continue Button”
  - Reduce space between buttons to $space-m (10px)
#### Warning modal for uploading same file name
- **[Must Have?]** Add warning modal when user adds a file with the same file name and will overwrite previously added file/samples
  - Janeece to provide design, but this can use browser default styling
  - @tihuan  has made a warning modal like this for Metadata re-importing

**Comment by Janeece** [comment]
@tihuan let us know if any of the bullet points I called out will be resolved when they are merged together :)

**Comment by Janeece** [comment]
@phoenixAja @tihuan heres the breakdown for updates to the error alert (many of these apply to errors in general). The first part is the updates I'd want to see on the component in place. At the end is a big nice to have -- start reshaping the component for the design system. Realistically, that change might require more input between eng and design than we have time for in v3. 

#### Screenshot:
Alert - Error


#### Overall alerts
- **[Should Have - Design Priority]** Update padding to 10px on all sides
- **[Must Have]** Align arrow icon to top right, position should remain the same no matter what length content or open/closed
- **[Low Priority]** Reduce space between decorative icon and content to $space-m (10px)
- **[Should Have - Design Priority]** Update decorative icon to use our icons
- **[Should Have - Design Priority]** Remove background for arrow icon’s hover state
- **[Low Priority]** Update arrow icon color (accordion alerts only)
  - Default = $gray-dark / $gray-500
  - Hover = $gray-darkest / $gray-600
- **[Should Have - Design Priority]** Increase primary error text size to font-body-s, and increase weight to font-weight: 600;

#### Error/Warning table
- **[Should Have - Design Priority]** Reduce header cell padding to $space-m (10px on all sides)
- **[Should Have - Design Priority]** Add a 1px $gray-lightest ($gray-200) border at bottom of header row
- **[Should Have - Design Priority]** Reduce content cell padding to $space-m (10px on all sides)
- **[Should Have - Design Priority]** Update row striping color 
  - Ideally this color =  $black @ 3% opacity (can be used universally for any alert type & will be the preference in the Design System)
   - If using spec’d color, needs to match the alert intent (error alert = $error-100-overlay, warning = $warning-100-overlay)

#### Design System Component
- **[Low Priority - nice to have]** Update component based on new designs system naming and property conventions (see spec artboard 9.2) https://www.figma.com/file/pH5rRGCzcMkCKkn6UMQVUR/v3-Upload?node-id=768%3A0 
  - Includes name update, property updates
  - open to eng feedback

**Comment by tihuan** [comment]
> [Must Have] Align arrow icon to top right, position should remain the same no matter what length content or open/closed 

This is fixed in step 3 PR 🎉 

> Nav Upload button
[Must Have] Needs to match to @tihuan implementation

This is done by pulling in the latest `upload` branch

> Continue/Cancel Buttons
[Must Have] Recommend matching @tihuan implementation.
Position buttons $space-xl (22px) from the bottom of the page
Remove space on left of “Continue Button”
Reduce space between buttons to $space-m (10px)

This is done by pulling in the latest `upload` branch

**Comment by phoenixAja** [comment]
ahhh sorry @tihuan i didn't see that you already fixed those lint issues yesterday! Hopefully this wont be too disruptive to our upload flow testing!

**Comment by tihuan** [comment]
Just merged this into `upload`, so we have less pending PRs 😆

**Pull request merged**
