### PR TITLE
Add aspen terraform batch configuration

### PR DESCRIPTION
**Pull request by ttung**
### Description
This batch configuration will be used to run workflows like download from gisaid.

Depends on #198 

### Test plan
Ran a couple small jobs through the pipeline.

### CODE REVIEW

**Review by phoenixAja — APPROVED** [review]

**Comment by phoenixAja** [comment]
this is all really similar to the nextstrain batch stuff besides using a different docker image for the job definition.. when integrating with the shared infra stuff i think we can remove a lot of this duplication by using the batch module

**Comment by ttung** [comment]
> this is all really similar to the nextstrain batch stuff besides using a different docker image for the job definition.. when integrating with the shared infra stuff i think we can remove a lot of this duplication by using the batch module

different disk space requirement as well.  i think it would probably make sense to use R5 instances here as well, since we probably need a lot of memory and not a lot of CPU.

**Comment by ttung** [comment]
but yeah, it would probably be good to figure out how to dedup the code.

**Comment by phoenixAja** [comment]
> but yeah, it would probably be good to figure out how to dedup the code.

once we convert it to use the shared infra recipes i think we can dedup a lot of this (by using the batch modules that they created)

**Pull request merged**
