### PR TITLE
Download External Accessions

### PR DESCRIPTION
**Pull request by lvreynoso**
### Description

Adds a column to download external accessions of a phylo tree in TSV format.

Screenshot from 2021-05-06 13-32-15

#### Issue
[ch<131413>](https://app.clubhouse.io/genepi/story/<131413>)

### Test plan

Tested locally with a Santa Clara DPH file.

### CODE REVIEW

**Review by shanaxel42 — COMMENTED** [review]
yay!!!! But I don't think this matches the design that's in Figma? https://www.figma.com/file/uHpPNuDSBupK97ORCkH1op/Aspen-v0-to-v2?node-id=114%3A4500

**Comment by lvreynoso** [comment]
Good point, will update

**Comment by tihuan** [comment]
@lvreynoso  This looks super good! The mock seems to be using the `Menu` and `MenuItem` components, which `czifui` library has 😄 

Example in: `src/frontend/src/components/NavBar/components/UserMenu/index.tsx`

```tsx
import { AppThemeOptions, Menu, MenuItem } from "czifui";

<Menu
        anchorEl={anchorEl}
        keepMounted
        open={Boolean(anchorEl)}
        onClose={handleClose}
        getContentAnchorEl={null}
      >
        <a href={ROUTES.CONTACT_US_EMAIL} target="_blank" rel="noopener">
          <MenuItem onClick={handleClose}>Contact us</MenuItem>
        </a>
        <Link to={ROUTES.TERMS} target="_blank" rel="noopener">
          <MenuItem onClick={handleClose}>Terms of Use</MenuItem>
        </Link>
        <Link to={ROUTES.PRIVACY} target="_blank" rel="noopener">
          <MenuItem onClick={handleClose}>Privacy Policy</MenuItem>
        </Link>
        <a href={process.env.API_URL + API.LOG_OUT}>
          <MenuItem onClick={handleClose}>Logout</MenuItem>
        </a>
      </Menu>
```

Please let me know if I can help in any way! Thank you!

**Comment by lvreynoso** [comment]
Updated.

Screenshot from 2021-05-10 16-00-22

**Review by tihuan — APPROVED** [review]
Download menu looks great! Thanks @lvreynoso 🔥 

Screen Shot 2021-05-10 at 4 59 14 PM

LGTM!

**Pull request merged**
