### PR TITLE
Fix pre-commit hooks

### PR DESCRIPTION
**Pull request by lvreynoso**
### Summary:
- **What:** Fixes and update our pre-commit hooks.
- **Ticket:** [sc166801](https://app.shortcut.com/genepi/story/166801)
- **Env:** `localdev`

### Demos:
In the following image you can see how `pre-commit` works. I added some python code to staging and attempted to commit it, which triggered the pre-commit hooks. `black` and `isort` made changes, so `pre-commit` didn't let the commit go through. All I had to do was add the fixed files and commit again!
Screen Shot 2021-10-28 at 16 52 12

### Notes: 
Run `brew install pre-commit` to use the hooks! They do not enforce any rules, just try and prettify and fix code, so they shouldn't block anyone from making a commit. The idea is to make using them seamless and pain-free.

### Checklist:
- [x] I merged latest `<base branch>`
- [x] I manually verified the change
- [x] I added labels to my PR
- [x] I tested in multiple browsers
- [x] I added relevant unit tests
- [x] I have notified others of changes they need to make locally (migrations, jobs, package updates, etc)

### CODE REVIEW

**Review by phoenixAja — APPROVED** [review]

**Comment by jgadling** [comment]
I get this when I try to use the hooks:

```
stderr:
    npm ERR! code ERESOLVE
    npm ERR! ERESOLVE unable to resolve dependency tree
    npm ERR!
    npm ERR! Found: eslint@8.1.0
    npm ERR! node_modules/eslint
    npm ERR!   peer eslint@"^6.0.0 || ^7.0.0 || ^8.0.0" from @typescript-eslint/eslint-plugin@5.2.0
    npm ERR!   node_modules/@typescript-eslint/eslint-plugin
    npm ERR!     @typescript-eslint/eslint-plugin@"*" from the root project
    npm ERR!     peerOptional @typescript-eslint/eslint-plugin@"^4.0.0 || ^5.0.0" from eslint-plugin-jest@25.2.2
    npm ERR!     node_modules/eslint-plugin-jest
    npm ERR!       eslint-plugin-jest@"*" from the root project
    npm ERR!   peer eslint@"^6.0.0 || ^7.0.0 || ^8.0.0" from @typescript-eslint/parser@5.2.0
    npm ERR!   node_modules/@typescript-eslint/parser
    npm ERR!     @typescript-eslint/parser@"*" from the root project
    npm ERR!     peer @typescript-eslint/parser@"^5.0.0" from @typescript-eslint/eslint-plugin@5.2.0
    npm ERR!     node_modules/@typescript-eslint/eslint-plugin
    npm ERR!       @typescript-eslint/eslint-plugin@"*" from the root project
    npm ERR!       1 more (eslint-plugin-jest)
    npm ERR!   5 more (babel-eslint, eslint-config-prettier, ...)
    npm ERR!
    npm ERR! Could not resolve dependency:
    npm ERR! eslint-plugin-jsx-a11y@"*" from the root project
```

**Comment by mmmmmmaya** [comment]
@jgadling did you try deleting `package-lock.json` and running `npm i` again? Sometimes the package-lock gets itself stuck in a stalemate and it can't get a good dependency version.

**Comment by lvreynoso** [comment]
> I get this when I try to use the hooks:
> 
> ```
> stderr:
>     npm ERR! code ERESOLVE
>     npm ERR! ERESOLVE unable to resolve dependency tree
>     npm ERR!
>     npm ERR! Found: eslint@8.1.0
>     npm ERR! node_modules/eslint
>     npm ERR!   peer eslint@"^6.0.0 || ^7.0.0 || ^8.0.0" from @typescript-eslint/eslint-plugin@5.2.0
>     npm ERR!   node_modules/@typescript-eslint/eslint-plugin
>     npm ERR!     @typescript-eslint/eslint-plugin@"*" from the root project
>     npm ERR!     peerOptional @typescript-eslint/eslint-plugin@"^4.0.0 || ^5.0.0" from eslint-plugin-jest@25.2.2
>     npm ERR!     node_modules/eslint-plugin-jest
>     npm ERR!       eslint-plugin-jest@"*" from the root project
>     npm ERR!   peer eslint@"^6.0.0 || ^7.0.0 || ^8.0.0" from @typescript-eslint/parser@5.2.0
>     npm ERR!   node_modules/@typescript-eslint/parser
>     npm ERR!     @typescript-eslint/parser@"*" from the root project
>     npm ERR!     peer @typescript-eslint/parser@"^5.0.0" from @typescript-eslint/eslint-plugin@5.2.0
>     npm ERR!     node_modules/@typescript-eslint/eslint-plugin
>     npm ERR!       @typescript-eslint/eslint-plugin@"*" from the root project
>     npm ERR!       1 more (eslint-plugin-jest)
>     npm ERR!   5 more (babel-eslint, eslint-config-prettier, ...)
>     npm ERR!
>     npm ERR! Could not resolve dependency:
>     npm ERR! eslint-plugin-jsx-a11y@"*" from the root project
> ```

That is strange. I might have to explicitly add `eslint` as a dependency.

**Comment by lvreynoso** [comment]
I'll also pin the dependencies to the ones we use in the frontend project.

**Comment by lvreynoso** [comment]
I'm not sure why `ts-lint` is suddenly complaining, I didn't change any of the tests!

**Comment by lvreynoso** [comment]
I removed `eslint` since this is mostly about enforcing code style.

**Pull request merged**
