### PR TITLE
168697 Maya/popup blocker

### PR DESCRIPTION
**Pull request by mmmmmmaya**
### Summary
- **What:** Makes changes to usher flow to prevent activating user pop up blocker
- **Why:** Ease of use
- **Ticket:** [[sc-168697]](https://app.shortcut.com/genepi/story/168697)
- **Env:** https://usher-frontend.dev.genepi.czi.technology?usher=true [pending]
- **Discussion:** https://czi-sci.slack.com/archives/C024P2G20F3/p1634690353017500

### Demos
Screen Shot 2021-10-20 at 11 11 57 AM
Screen Shot 2021-10-20 at 11 12 06 AM

### Checklist
- [x] I merged latest `trunk`
- [x] I manually verified the change
- [x] I added labels to my PR
- [ ] I tested in multiple browsers
- [ ] I added relevant unit tests
- [ ] I have notified others of changes they need to make locally (migrations, jobs, package updates, etc)

### CODE REVIEW

**Comment by phoenixAja** [comment]
this looks good, but the rdev is broken 😢

**Comment by mmmmmmaya** [comment]
Yea, rdev isn't deploying right now because of the curl/gisaid issue https://czi-sci.slack.com/archives/C01HYJYA50W/p1634748158400800

**Comment by phoenixAja** [comment]
that shouldn't affect the rdev deploy.. i'll approve though because the pr looks good

**Review by phoenixAja — APPROVED** [review]

**Comment by phoenixAja** [comment]
oh so the gisaid docker build is failing but not because of the curl issue, ok interesting

**Comment by Janeece** [comment]
@mmmmmmaya -- here's my feedback! 

Prioritization notes:
- *must have* = blocker because broken or confusing
- *should have* = non-blocker but should be updated to be correct to design
- *nice to have* = non-blocker

### Feedback

#### Confirmation Dialog
Looks great, no comments. 

#### Notification
- [ ] Should have — position the notification 14px below browser top edge
- [ ] Should have — link hover state should be black text and solid line instead of purple
- [ ]  Should have — reduce space above and below "Dismiss" Button. Above = 10px, below = 14px (if this is an update needed on SDS, this is not a priority update)
Screen Shot 2021-10-20 at 3 51 27 PM

**Pull request merged**
