### PR TITLE
Flatten *aspen-config

### PR DESCRIPTION
**Pull request by ttung**
### Description
SecretsManager doesn't have a nice facility for editing nested json.

### Test plan
grepped for `DB.`

### CODE REVIEW

**Review by jgadling — CHANGES_REQUESTED** [review]
Keeping a "." in key names makes it really easy to misunderstand whether we're navigating a nested data structure or referring to a literal key.

**Comment by ttung** [comment]
Replaced `.` with `/`.  Rationale: same separator as AWS parameter store.

**Comment by jgadling** [comment]
Slashes in json keys is also pretty nonstandard. can we use - or _ ?

**Comment by ttung** [comment]
Only `_` is allowed by jq.  Even `-` is not allowed.

**Comment by ttung** [comment]
I guess if the criteria is "allowed by jq" then we will just have to use `_`.

**Comment by ttung** [comment]
Switched to using `_`

**Review by shanaxel42 — APPROVED** [review]
looks good

**Pull request merged**
