### PR TITLE
Thuang metadata

### PR DESCRIPTION
**Pull request by tihuan**
### Description

Write a description of your pull request here

#### Issue
[ch<fill_in_issue_number>](https://app.clubhouse.io/genepi/story/<fill_in_issue_number>)

### Test plan

Write how your changes are tested, or give a convincing reason why they can't be tested automatically.

### CODE REVIEW

**Comment by Janeece** [comment]
@tihuan Here's my review feedback. Its grouped by component/area on the page. I also tried to include some prioritization, but let me know if you have questions, concerns, or specs (some items include info i need to provide you with).

#### Prioritization Key:
- **[Must Have]** - change needed to meet required v3 specs
- **[High Priority]** - change needed to create a clear user experience & reflect design
- **[Design Priority]** - update needed to accurately reflect design, does not impact ability to use the function.
- **[Low priority]** - nice to haves, minor refinements

## Feedback:

Collection Location Menu
Aspen-Upload-Metadata


### Page Header
- Samples should be clickable to go back to step 1 **[Low priority]** 
  - see figma artboard 2.8 for specs

### Info Containers (General)
- Update copy in both containers (see design for most recent) **[Must Have]**
- Add border-radius to containers ($border-radius-m / 4px) **[Low priority]**
- Increase space below subheads to $space-m (10px) **[Low priority]**

##### Sample Privacy info
- Reduce text size in Sample privacy container to match Import Instructions (subhead = $font-header-xs; lists = $font-body-xs) **[Design Priority]**

##### Import Instructions info
- Add margin between “import instructions” list and “Re-Importing Data” subtitle ($space-l / 14px) **[High Priority]**
- Reduce space between #s and text on ordered list ($space-xs /4px) and add “.” after # **[Design Priority]**

### Metadata Table

- Row alignment when error or apply all is visible below the input **[High Priority]**
  - Input should remain aligned with other inputs
  - Row height increases below the input
- Column spacing -- left and right margins = $space-m (10px) **[High Priority]**
  - “Sample Is Private” needs it
  - “Previously submitted…” needs it
- Add min/max width to containers
  - “Sample is Private” - min/max width = 62px **[High Priority]**
  - “Previously Submitted…” - min/max width = 140px **[High Priority]**
  - Sequencing date / Collection date - min width = 110px **[Low priority]**
  - Collection Location - min width = 200px **[Low priority]**
 - Hide sample Public ID and ISL Accession # when “Previously Submitted to GISAID?” **[High Priority]**
 - Reduce padding on header cells to $space-m (10px) **[Low priority]** 
- Toggle component style -- update to match design system **[Design Priority]**

##### “Collection Location” dropdown menu
- Add a max height -- 300px **[High Priority]**
- Update county List **[Must Have]**
  - Only include :
   - California (New, design to be provideded)
     - Detail text: County not specified
   - Alameda County
   - Contra Costa County
   - Fresno County
   - Humboldt County
   - Marin County
   - Monterey County
   - Orange County
   - San Bernardino County
   - San Francisco County
   - San Joaquin County
   - San Luis Obispo County
   - Santa Clara County
   - Tulare County
   - Tuolumne County
   - Ventura County

### Buttons
- Add space between “Continue” and “Back” button ($space-m / 10px)  **[High Priority]**
- Add space between buttons and bottom of the page ($space-xl / 22px) **[High Priority]**
- Upload Button in nav 
  - Keep as “Upload” [Must Have] 
  - @Janeece Need to provide designs for states **[High Priority]**

### Other
- Need line between “Hide instructions” and “Download Metadata Template” **[High Priority]**
  - 1px $gray-medium ($gray-400)
  - Height = 14px
  - Left and right margins = $space-xs (6px)

**Comment by tihuan** [comment]
Ooh love your super clear and detailed feedback, Janeece!! Really appreciate it 🤩 🙏 Will get the Must Have's in before Tuesday!

For the County List option -- California, we'll need a new field for that, right? So I'll wait for the design to see where we wanna put the field?

Thank you!!

**Comment by Janeece** [comment]
@tihuan California will be a new menu item type that we have in the design system. I'll be able to send you the design this morning!

**Comment by Janeece** [comment]
@tihuan One more **low priority** item that came in this morning was to change the page title in the header from "Upload Metadata" to "Metadata and Sharing"

**Comment by tihuan** [comment]
Got it! Page title is now updated to "Metadata and Sharing" 😄 Thank you!

Screen Shot 2021-06-11 at 1 09 44 PM

**Comment by tihuan** [comment]
Reimport TSV confirmation dialog is up!

Screen Shot 2021-06-11 at 1 09 22 PM

demo

**Comment by tihuan** [comment]
Live link updated and should reflect the changes above now 🎉 

https://thuang-metadata-1-frontend.dev.genepi.czi.technology/upload/2

@Janeece I only addressed Must Have's and the page title to `Metadata and Sharing`, and adding bottom buttons and its spacings!

Thank you!

Screen Shot 2021-06-11 at 1 52 37 PM

**Comment by Janeece** [comment]
Woah the import warning dialog is so cool looking! 

Also, little clarification on the page title -- I forgot that "page title" is a defined thing! the change you made looks awesome, but the comment meant to change it  in the header here:
Screen Shot 2021-06-11 at 1 52 01 PM

If you're able to update that a well, that'd be great! Again, low priority.

**Comment by tihuan** [comment]
Yeah! Great idea on the confirm, Janeece 💯 

Ooh sorry I missed that lol Done!

Screen Shot 2021-06-11 at 1 57 49 PM

**Comment by Janeece** [comment]
Amazing! So are the other updates you've made on the Must Haves. The spacing around the bottom buttons is so much better!

I found one typo (carried over from the design) in the import instructions-- need to add in the word "button"
Aspen-Metadata-and-Sharing

**Comment by tihuan** [comment]
Yay! Thanks so much for the encouragement 🎉 !!

Ahh eagle eye 🦅 👁️ 👌 

Thank you for catching that 😄 

DONE!

Screen Shot 2021-06-11 at 2 10 06 PM

**Pull request merged**
