### PR TITLE
thuang-new-favicon

### PR DESCRIPTION
**Pull request by tihuan**
### Description

New favicon with transparent background 🎉 

#### Issue
https://app.clubhouse.io/genepi/story/137590/update-favicon-design-ready

### Test plan

Screen Shot 2021-05-13 at 10 01 13 AM

### CODE REVIEW

**Comment by tihuan** [comment]
PTAL again! Thanks all!

**Comment by happyimadesignr** [comment]
yaaay thanks @tihuan

**Review by Janeece — APPROVED** [review]
This looks great, thanks Timmy!

**Comment by tihuan** [comment]
YAY!! Thanks all 👏 👏 👏 !! So exciting!!

@shanaxel42 can you help give @Janeece write access please? Otherwise her LGTM is not enough to unblock merge 😆 Thank you!!

**Comment by shanaxel42** [comment]
> YAY!! Thanks all 👏 👏 👏 !! So exciting!!
> 
> @shanaxel42 can you help give @Janeece write access please? Otherwise her LGTM is not enough to unblock merge 😆 Thank you!!

Done!

**Comment by tihuan** [comment]
Awesome!! Thanks so much, @shanaxel42 🎉 !!

**Pull request merged**
