### PR TITLE
Add autoflake to `make backend-run-style`

### PR DESCRIPTION
**Pull request by jgadling**
### Summary:
- **What:** This updates `make backend-run-style` to clean up unused imports & variables. This is handy because `make backend-check-style` which is part of our CI pipeline checks for these errors and we don't otherwise have a way to automatically clean them up
- **Ticket:** [sc<fill_in_issue_number>](https://app.shortcut.com/genepi/story/<fill_in_issue_number>)
- **Env:** `<rdev link>`

### Checklist:
- [ ] I merged latest `<base branch>`
- [ ] I manually verified the change
- [ ] I added labels to my PR
- [ ] I tested in multiple browsers
- [ ] I added relevant unit tests
- [ ] I have notified others of changes they need to make locally (migrations, jobs, package updates, etc)

### CODE REVIEW

**Comment by vincent-czi** [comment]
How noisy is it when `autoflake` runs? Does it print out what changes it's making, or does it just make the changes silently and in-place? I'm ambivalent on this kind of tool. It's not common, but I know I have made a couple mistakes working in the past where seeing that I had an unused var made me realize I had screwed up (like accidentally leaving a code block commented out), and seeing a flake8 warning saved me an experience of "wait, what the heck is going on?". Auto-removing this sort of stuff without any notification of the change feels like a double-edged sword.

Counter-point: if the dev adds code, then runs tool, then diffs all the above is still visible. Similarly, if dev runs the check-style instead, the visibility is still available. Like I said, I'm ambivalent.

**Review by vincent-czi — APPROVED** [review]
I've got a separate comment with my philosophical waffling, but code-wise, this is all good

**Review by lvreynoso — APPROVED** [review]

**Comment by lvreynoso** [comment]
> How noisy is it when `autoflake` runs? Does it print out what changes it's making, or does it just make the changes silently and in-place? I'm ambivalent on this kind of tool. It's not common, but I know I have made a couple mistakes working in the past where seeing that I had an unused var made me realize I had screwed up (like accidentally leaving a code block commented out), and seeing a flake8 warning saved me an experience of "wait, what the heck is going on?". Auto-removing this sort of stuff without any notification of the change feels like a double-edged sword.
> 
> Counter-point: if the dev adds code, then runs tool, then diffs all the above is still visible. Similarly, if dev runs the check-style instead, the visibility is still available. Like I said, I'm ambivalent.

You can always run `make backend-check-style` first :)

**Comment by jgadling** [comment]
> How noisy is it when `autoflake` runs? Does it print out what changes it's making, or does it just make the changes silently and in-place? 

It was silently fixing things, but I added the `-v` flag so it'll print the names of files that it changes.

**Comment by vincent-czi** [comment]
> It was silently fixing things, but I added the `-v` flag so it'll print the names of files that it changes.

Appreciate it, thanks!

**Pull request merged**
